### ISSUE TITLE
Error when downloading runtime from server connector

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/rsp-server#421] opened 2019-06-27 10:52 UTC
Found this error while downloading wildfly runtime. I tried to manually download it and i had no problem opening the zip. OS: Fedora 30.

```
Job Download runtime: WildFly 9.0.2 Final completion is at 81
jobprogress.js:64
Message=Received notification 'client/jobChanged'. data=Params: {
    "percent": 90,
    "handle": {
        "name": "Download runtime: WildFly 9.0.2 Final",
        "id": "e8cf9549-7abd-4295-9e68-9852a1e68afa"
    }
}


client.js:41
Job Download runtime: WildFly 9.0.2 Final completion is at 90
Message=Received notification 'client/jobRemoved'. data=Params: {
    "status": {
        "severity": 4,
        "plugin": "org.jboss.tools.rsp.runtime.core",
        "code": 0,
        "message": "Error while retrieving runtime from http://download.jboss.org/wildfly/9.0.2.Final/wildfly-9.0.2.Final.zip",
        "trace": "org.jboss.tools.rsp.eclipse.core.runtime.CoreException: Error opening zip file /home/luca/.org.jboss.tools.rsp.data/runtimes/downloads/wildfly-9.0.2.Final.zip;  file may not be a properly formated zip file.\n\tat org.jboss.tools.rsp.runtime.core.util.internal.DownloadRuntimeOperationUtility.unzip(DownloadRuntimeOperationUtility.java:221)\n\tat org.jboss.tools.rsp.runtime.core.util.internal.DownloadRuntimeOperationUtility.downloadAndUnzip(DownloadRuntimeOperationUtility.java:168)\n\tat org.jboss.tools.rsp.runtime.core.model.installer.internal.ExtractionRuntimeInstaller.installRuntime(ExtractionRuntimeInstaller.java:40)\n\tat org.jboss.tools.rsp.server.spi.runtimes.AbstractLicenseOnlyDownloadExecutor$1.run(AbstractLicenseOnlyDownloadExecutor.java:150)\n\tat org.jboss.tools.rsp.server.spi.jobs.SimpleJob.run(SimpleJob.java:96)\n\tat org.jboss.tools.rsp.server.jobs.JobManager.lambda$0(JobManager.java:86)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.util.zip.ZipException: zip file is empty\n\tat java.util.zip.ZipFile.open(Native Method)\n\tat java.util.zip.ZipFile.<init>(ZipFile.java:225)\n\tat java.util.zip.ZipFile.<init>(ZipFile.java:155)\n\tat java.util.zip.ZipFile.<init>(ZipFile.java:169)\n\tat org.jboss.tools.rsp.runtime.core.extract.internal.UnzipUtility.extract(UnzipUtility.java:54)\n\tat org.jboss.tools.rsp.runtime.core.extract.ExtractUtility.extract(ExtractUtility.java:87)\n\tat org.jboss.tools.rsp.runtime.core.util.internal.DownloadRuntimeOperationUtility.unzip(DownloadRuntimeOperationUtility.java:217)\n\t... 8 more\n"
    },
    "handle": {
        "name": "Download runtime: WildFly 9.0.2 Final",
        "id": "e8cf9549-7abd-4295-9e68-9852a1e68afa"
    }
}
```

**Comment by robstryker** [comment] 2019-07-02 04:11
I suggest you start the rsp in itself in debug mode and then connect a remote debugger to the rsp and set a breakpoint where the error occurs where it tries to unzip the file.  Then, check the file size, file format, etc etc etc, and see what might have caused it.

**Comment by robstryker** [comment] 2019-07-11 21:01
Replicated and fixed, kinda.  It's only fixed at the jboss-stacks level, where we get the urls.  The long and the short of it is, we check the content length of the remote file.  If it's less than zero, that means "unknown" and we read the stream until it's done.  If it's not less than zero, we read exactly content-length number of bytes from the stream. 

The problem is, these files were redirects. My code *does* have follow-redirects enabled. However, I am reading 0 bytes, because the initial response has a 0 content-length (because it's a redirect) so I am reading 0 bytes from the stream. 

This can probably be fixed by using a proper downloading library, but for now, this is what I've got. 

I'm closing this issue because it's "fixed" but I think we should open another one to maybe replace the downloading mechanism.

**Closed by robstryker** 2019-07-11 21:01 UTC
