### ISSUE TITLE
Runtime downloaded twice

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#359] opened 2019-05-17 09:01 UTC
Although I already downloaded a server and it is cached in the `downloads` folder, it is downloaded again

**Comment by robstryker** [comment] 2019-05-17 15:06
I don't actually see a problem with this. If the user wants to download it again, he probably wants a fresh install or to have a server separate from his existing one. 

If your issue is that it should be easier to create a server adapter out of a runtime that was previously downloaded but had it's adapter deleted, then I agree.  But I don't think the download-runtime feature should be rejected only because a runtime has already been downloaded.

**Comment by adietish** [comment] 2019-05-18 09:33
@jeffmaury @robstryker makes perfect sense to detect that a runtime was already downloaded and can be re-used when creating a new server (download should not be rejected).

**Comment by adietish** [comment] 2019-05-18 09:50
this is related to #360. If we want to reuse runtimes that we downloaded, we would have to detect (and evict) partial downloads.

**Comment by jeffmaury** [comment] 2019-05-18 15:17
My problem is the following: when we first download a runtime, a zip file is downloaded and stored in `runtimes/downloads` folder, then unzipped in a new folder in `runtimes/installations` and the download file is not delete.
Next time I ask to download the same runtime, the zip is downloaded again and ..
So we should be coherent:

- reuse the previously downloaded file
- or delete it after it has been downloaded

**Comment by robstryker** [comment] 2019-05-20 15:47
Ok... I like the idea of re-using the zip file if possible. This saves the user quite some workflow. I'll work on this.

**Comment by robstryker** [comment] 2019-05-20 16:07
I've looked through the issue, and after some testing, there are only 3 paths used (currently) for download runtimes, and they all stem from the same single call, just through 3 possible implementations. 

				IStatus ret = installer.installRuntime(dlrt, uniqueLoc.getAbsolutePath(), downloads.getAbsolutePath(), true, tm2, sub.split(90));

The "true" there is to deleteOnExit. Basically, all of downloadRuntimes actually deletes on exit. I just tested it, and, in all normal workflows, it works 100% as expected. The zip is downloaded, it is expanded, and when the VM shuts down properly, the zip file is deleted. 

If the RSP is terminated or killed, though, the zip file might not be removed. But this is expected VM behaviour.

**Comment by robstryker** [comment] 2019-05-20 18:32
@adietish Can you confirm? 

Steps to replicate:  
1) rm -rf your ~/.org.jboss.tools.rsp.data/ folder
2) run wildfly server main
3) run CLI
4) type download runtime
5) pick a random wildfly
6) perform all necessary steps to begin download (sign license etc)
7) once complete, and server is added,  type "shutdown" in CLI
8) verify that ~/.org.jboss.tools.rsp.data/runtimes/downloads/ is empty

**Comment by adietish** [comment] 2019-05-21 09:48
@robstryker I can confirm this. Once the server is shut down, the zip is removed.

> 1.
> 2. 
> 3.
> 4. picking wildfly 16
> 5.  
> 6. download is started. Once finished I see the zip appears in downloads
```
$ ll ~/.org.jboss.tools.rsp.data/runtimes/downloads
total 360496
-rw-r--r--  1 adietish  staff   173M May 21 11:39 wildfly-16.0.0.Final.zip
> 7. shutdown
$ ll ~/.org.jboss.tools.rsp.data/runtimes/downloads
$
```

**Comment by adietish** [comment] 2019-05-21 10:27
I tested if partial downloads are removed and I could not confirm this: https://github.com/redhat-developer/rsp-server/pull/363#issuecomment-494334336

**Comment by robstryker** [comment] 2019-05-21 15:01
I've investigated changing the API to NOT delete the zip, and instead re-use it on the next download, but that kinda breaks the API / workflow currently in existence and would kinda require a very different internal SPI. The API wouldn't need to change, but, I struggle to find an SPI that would work. 

I'm honestly not even sure if it's a good idea to re-use the zip or not. I kinda like it, but I also kinda don't.

**Comment by robstryker** [comment] 2019-05-23 16:16
So we should be coherent:
    
        reuse the previously downloaded file
        or delete it after it has been downloaded

@jeffmaury  We now delete the file after it has been downloaded. Would you say this issue is now resolved?

**Comment by jeffmaury** [comment] 2019-06-04 17:55
+1

**Comment by adietish** [comment] 2019-06-11 20:25
We're now deleting a previously download zip. Since this is 1 of the suggested solution we can now close this issue as FIXED.

**Closed by adietish** 2019-06-11 20:25 UTC
Labels: enhancement
