### ISSUE TITLE
Run tests using Felix

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#41] opened 2018-09-14 13:58 UTC
Tests are run using the Equinox framework we should try to run them closer to what the user will run thus using Felix

**Comment by robstryker** [comment] 2018-09-20 19:16
From what I've read, it will be extremely difficult to get the tests to actually run in tycho and in felix. Almost every article I've read where people tried it, they've simply given up. Even people close to tycho who have tried to make it work have decided it's too much work. I'm not sure what the blockers here are, but, the fact that we're running inside an osgi container at all is already (imo) the best we can do. 

I do not think this issue will get solved unless we get someone like @mistria to help.

**Comment by robstryker** [comment] 2018-09-20 20:47
Actually I think @jrichter1  was makign integration tests that actually test the distribution.

**Comment by robstryker** [comment] 2018-10-16 16:44
I'm closing this as a duplicate of https://github.com/redhat-developer/rsp-server/issues/14

Jan's integration tests will further run these tests in felix, I believe.

**Closed by robstryker** 2018-10-16 16:44 UTC
Labels: enhancement
