### ISSUE TITLE
Re-creating the WAR does not change state

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/rsp-server#168] opened 2018-11-15 21:29 UTC
This is related to #160 
Here are the steps
1) create a WF server
2) start the server
3) add deployment from https://github.com/jboss-developer/jboss-eap-quickstarts/kitchensink (target/jboss-kitchensink.war)
4) publish the server
5) run `mvn clean package`

Then no change is propagated to the CLI

**Comment by robstryker** [comment] 2018-11-16 21:09
replicated. Requires test case. Think I discovered the error. subscribeToChanges is not covering all bases.

**Comment by robstryker** [comment] 2018-11-16 21:49
Was an interesting bug. Was clearly missing a case in my logic. Damn.

**Comment by robstryker** [comment] 2018-11-16 21:49
* bee0468 - (HEAD -> issue151, mine/issue151) Test case for #168 (27 seconds ago) <Rob Stryker>
* 18c637b - Issue 168 - clean mvn build mark deployment as requiring publish (11 minutes ago) <Rob Stryker>

**Comment by adietish** [comment] 2018-11-26 13:07
verified it, things work for me. mvn clean package gets notified with the following event:
```
<base-path>/kitchensink/target/kitchensink.war [started] [incremental]
```
Once I publish the server, the changes are active

**Comment by adietish** [comment] 2018-11-26 13:16
@robstryker 
how do you determine if the change is an incremental change (```[incremental]```)?

**Comment by robstryker** [comment] 2018-11-27 16:11
>  FilewatcherModificationsTest doesn't work for me, all asserts are failing. What am I missing?

Seems an issue for you only?

>    how do you determine if the change is an incremental change ([incremental])?

All changes are caused by a file change are incremental in nature. For our current supported deployments (single files), an incremental change is basically a full change anyway. Extenders could theoretically listen to the file changes themselves and determine that a change to a specific file (like manifest.mf or application.xml) requires a full publish, but there's currently no API for them to do so. 

>    shouldn't the initial started/stopped state for the deploybale be [unknown] rather than [null]?

error in client, missed switch on sysout

>    shouldn't the run state of a deployment be [stopped] rather than [started] if the server is not running ?

please provide a more complete workflow. After small fixes to client, initial state of deployment is 'unknown'.  Please open new issue. 

Thanks for feedback!

**Comment by robstryker** [comment] 2018-11-27 17:20
I've fixed some of the initial state issues. Closing this issue.

**Closed by robstryker** 2018-11-27 17:20 UTC

**Comment by adietish** [comment] 2018-11-28 16:13
@robstryker @jeffmaury so yes, it only happens in MacOS: WatchService is highly delayed and misses events on MacOS. There's an issue in openjdk that's still open as of Java 11: https://bugs.openjdk.java.net/browse/JDK-7133447

At https://stackoverflow.com/questions/9588737/is-java-7-watchservice-slow-for-anyone-else they suggest registering the service in the following way:
```
folder.register(watcher, new WatchEvent.Kind[]{StandardWatchEventKinds.ENTRY_MODIFY}, SensitivityWatchEventModifier.HIGH);
```
The problem with that is that ```com.sun.nio.file.SensitivityWatchEventModifier``` is not portable across jdks.
I tried it to no avail, i still have all tests failing with assertion errors.
There are a few replacements but none are perfect nor drop-ins.
* directory-watcher https://github.com/takari/directory-watcher (not a drop-in replacement, Linux/Windows & Mac watch-loop differ)
* sbt > 1.1.3 https://github.com/sbt/sbt (no drop-in, scala). 
  * Extensive discussion here: https://github.com/sbt/sbt/issues/3527
* BarbaryWatchService https://github.com/gjoseph/BarbaryWatchService (almost drop in for MacOS but unmaintained and GPL). 
  * Extensive discussion is here: https://github.com/gjoseph/BarbaryWatchService/issues/6
* RxJavaFileUtils https://github.com/ReactiveX/RxJavaFileUtils (no drop-in replacement, doesn't work for windows, unmaintained)

Thoughts?

**Comment by jeffmaury** [comment] 2018-11-29 06:58
Or if you can't start with this flag on (because the flag does not exists), then emit an always visible message that user may experience strange behaviors on publishing and consider switching to OpenJDK

**Comment by jeffmaury** [comment] 2018-11-29 06:59
After all our market is 90% Windows based on which probably 95% of Java desktops are OpenJDK based
